enaqx/awesome-pentest

- README.md
Hi guys,
Awesome repository but it was missing these two tools. I hope it is not intrusive. Anyway, let us know.
Thanks
> Added WebReaver and Secapps

- README.md
fix the network tool title (anchor link )
> network tools - anchor link

- .github/CONTRIBUTING.md
- README.md
I've added various tools and resources. Many of them are from other PRs selected. And, some are the ones I added.
> Add various tools and resources and also contributing guideline

- README.md
> adding sqlmap

- README.md
* shellsploit 
* arachni
* pwnat
* dsniff
* tgcd
* wifiphisher
* cms-explorer
* joomscan
* WhatWeb
* BlindElephant
* Windows-Exploit-Suggester
* Responder
* Empire
* Linux_Exploit_Suggester
* recon-ng
* Books
> Add tools and books

- README.md
`tls_prober` is a command line utility written in Python used for fingerprinting a server's SSL/TLS implementation. It can be used to identify what specific server software (OpenSSL, GnuTLS, etc.) and version a given SSL or TLS-capable server is using.
> Suggest `tls_prober` tool be added (fingerprint a TLS implementation).

- README.md
https://github.com/rabbitstack/fibratus
> Added fibratus

- README.md
`smbmap` is a handy SMB enumeration tool that also simplifies distributed file searching, remote code execution, and a number of other interactions over the SMB protocol.
> Suggest `smbmap` utility be added.

- README.md
Added BalCCon and FSec conferences
> Added BalCCon and FSec conferences

- README.md
I add the Parrot distribution. It is similar to Kali, but the display is lighter because it use XFCE with some custom graphics. All tools seems to be there :)
> Add Parrot Security OS

- README.md
You cannot leave scapy off the list, it is one of the best tools to build or analyse custom ip packets.
> added scapy, python interactive packet manipulation

- README.md
Submitting [vcsmap](https://github.com/melvinsh/vcsmap) to the list.
> Add vcsmap

- README.md
A hacky debugger UI for hackers (https://github.com/snare/voltron)
> Add Voltron Debugger

- README.md
Hi,
merge request... i was add dripcap, Caffeinated packet analyzer....
> Add dripcap

- README.md
https://github.com/USArmyResearchLab/Dshell
> Added Dshell to Network Tools

- README.md
https://github.com/nixawk/pentest-wiki
If a shodan user, you may be interested in [Ports Number](https://github.com/nixawk/pentest-wiki/blob/master/3.Exploitation-Tools/Network-Exploitation/ports_number.md).
> add PENTEST-WIKI

- README.md
Added the first two fascicles of the three part series.
> Added Holistic Info-Sec for Web Developers.

- README.md
Added OWASP's newer purposely vulnerable web app (NodeGoat) with tutorials, excellent docs and community.
> Added NodeGoat docker image.

- README.md
Beautiful Christchurch NZ's only hacker con.
> Added CHCon to conferences.

- README.md
to list of Docker images for Pentesters
> Add OWASP Juice Shop

- README.md
"Both blue and red teams can use BloodHound to easily gain a deeper understanding of privilege relationships in an Active Directory environment."
> Add Bloodhound, a graphical AD trust relationship explorer.

- README.md
A simple addition of "Fedora Security Lab" distribution
> Added Fedora Security Labs in pentest distributions

- README.md
Added 'Defcon Suggested Reading' to books section https://www.defcon.org/html/links/book-list.html. Commits are wonky because I thought I cloned an outdated repo that added some lines. Double checked and it was just my editor removing trailing whitespaces.
> Added 'Defcon Suggested Reading' to books section https://www.defcon.org/html/links/book-list.html

- README.md
Added Vuls Vulnerability Scanner, a vulnerability scanner for Linux/FreeBSD, agentless, written in Go https://github.com/future-architect/vuls.
> added Vuls Vulnerability Scanner

- README.md
Added Kali Linux Docker Image https://www.kali.org/news/official-kali-linux-docker-images/. Made a mistake with the first commit (90afb7e) and modified the 'OWASP Juice' line before copying. Corrected with following commit (665ddcc).
> Added Kali Linux Docker Image

- README.md
Not sure if this should have been placed under "Windows Utilities," or if another part of the document is more appropriate. Let me know if it needs to move.
> Add wePWNise, Python tool to automate Windows/Office exploit mitigation.

- README.md
I didn't find "CTF framework for use in CTFs" to be very explanatory…. :|
> CTF section: Add RsaCtfTool, improve description of Pwntools.

- README.md
Not certain if this fits, but Buscador is built by the Intel Techniques folks, whose other tools are already on this list. Basically, Buscador is a pre-configured Linux that has a *bunch* of OSINT tools already installed and is designed especially for people doing online recon using open, public sources, which makes it really useful for the earlier (info gathering) parts of pentesting. The fact that it bundles a lot of other tools listed on this list already made me think it's appropriate for the "Distributions" section. `¯\_(ツ)_/¯`
> Add Buscador, a Linux VM pre-configured for online investigators.

- README.md
updated w some goodies; wpsploit, wordpress-exploit-framework, some OSITs, a DDoS tool... Enjoy!
> updated with a nice number of goodies

- README.md
Cugu's `awesome-forensics` is awesome because it emphasizes free (gratis) and open-source tools. It contains numerous tools that are relevant to pentesting but not directly in scope, such as The Sleuth Kit, etc.
> Add "Awesome Forensics" list by @Cugu.

- README.md
Links of Interest : 
* https://www.owasp.org/index.php/OWASP_OWTF
* https://github.com/owtf/owtf
> Add OWASP OWTF to list of tools

- README.md
This catches a few more missed items from the prior compliance pass. Further, there is focus on terminological consistency, including:
* Use consistent capitalization for abbreviations (OSInt -> OSINT).
* Consistently expand ambiguous phrases (OS -> operating system).
* Settle on standard names (Wi-Fi -> WiFi, etc.) where a mix was used.
* Expand acronyms in item titles when doing so shortens the description.
* Replace descriptions that merely expanded acronyms with actual text.
* Remove duplicate items that have more than one URL (Commix project).
* Do not Title Case description text when description is simply prose.
> Further "Awesome List" style guide compliance passes.

- README.md
Also sets the correct heading level for the Network Tools heading.
> Fix minor typos, capitalization issues, and term consistency.

- README.md
This commit conforms the Anonymity Tools section to the Awesome List
style guide by adding periods and such, plus adds the WEBKAY project to
help defend against identity and privay leaks from mis-configured Web
browsers. It also phrases the Tor project item description more clearly.
> Awesome List style guide compliance pass on the Anonymity Tools section.

- .travis.yml
> update travis steps to handle dfn subca

- README.md
SPARTA is not really its own tool, it's more like a meta-tool. There are
many "network infrastructure penetration testing tools" on this list,
but what does SPARTA actually do that these other tools don't? The
answer is primarily that SPARTA is a GUI wrapper around arbitrary
command lines with some additional logic to identify results from
well-known tools such as `nmap` and trigger actions based on those
results in other tools. Let's make that clear in the item's description.
> Provide a useful description for SPARTA.

- README.md
This commit continues work towards #86, making the list Awesome compliant, by using an SVG rather than a PNG image for the license badge and moving the image down to the bottom of the list under its own heading, rather than the top. See the conversation in sindresorhus/awesome#1013 for details.
> Move license to the bottom, replace the PNG with an SVG.

- README.md
To maintain conformance with the Awesome List Style Guide, this commit adds a period at the end of the new link to `awesome-osint`.
> Move "Awesome OSINT" item into the Awesome Lists section, add a period.

- README.md
Fluxion - Suite of automated social engineering based WPA attacks.  
I found this tool to be useful in gaining WPA/WPA2 credentials without needing to crack the handshake.  Automates the process of using social engineering to trick users into giving up their WPA passphrases.  Also confirms the correct passphrase was harvested by automatically comparing the passphrase to a captured handshake. 
I think this tool fits better in the Wireless Network Tools rather than as a Social Engineering Tool.
> Added Fluxion to Wireless Network Tools

- README.md
Added Penetration Testing Report Template section
> Added Penetration Testing Report Template section

- README.md
jwt-cracker: https://github.com/lmammino/jwt-cracker
rar-crack: https://github.com/ziman/rarcrack
bruteforce-wallet: https://github.com/glv2/bruteforce-wallet
> Added New Hash Cracking Tools

- README.md
Added two web exploitation tools from my own collection (both popular and maintained tools on github)
> Added NoSQL Map and VHostScan

- README.md
> Add intrigue to OSINT tools

- README.md
Adding ACLight tool - A script for advanced discovery of sensitive Privileged Accounts - includes Shadow Admins
A cool and easy tool for discovering the most sensitive accounts in the target network, those accounts may be unprotected.
> Adding ACLight tool

- README.md
This commit also conforms several other Network Tools line items to the
Awesome List style guide (remove the introductory "A" preposition).
> Add dnstwist.

- README.md
Progpilot is a static security analysis tool for PHP code, fully customizable.
> Add Progpilot

- README.md
PR that addresses issue #223 
https://github.com/caffix/awesome-pentest
https://github.com/caffix/amass
Thanks!
> Amass being added to the OSINT category

- README.md
* ScanCannon - `masscan` and `nmap` multiplexer.
* RID_ENUM - null session cycling attack for Windows user enumeration.
* MailSniper - recon toolkit for MS Exchange (OWA/EWS) environments.
* FiercePhish - full-fledged phishing campaign management platform.
* Hunter.io - data broker providing internal company emails.
> Add numerous tools, namely:

- README.md
> Added awesome tools

- README.md
https://github.com/c-sto/recursebuster
Content discovery/recursive web directory bruteforcer
> Add recursebuster

- README.md
This is a companion/sister list to awesome-pentest intended to provide
the same level of quality resources for defenders rather than attackers.
> New awesome list: "Cybersecurity Blue Team"

- README.md
I've added my new tool, Raccoon, to the Web Exploitation tools list
https://github.com/evyatarmeged/Raccoon
> Add Raccoon under Web Exploitation category

- README.md
A Framework for Man-In-The-Middle attacks
> Added MITMF

- README.md
List on Android Exploitation and Hacks
> Added Awesome list

- README.md
This PR fixes two sections, the Templates and Docker sections, by correcting capitalization and punctuation, as well as reviewing the linked items.
> Templates and docker fixes.

- README.md
Add Android Tamer OS in Penetration Testing Distributions.
> Add OS in Penetration Testing Distributions

- README.md
Hello, i added code examples for penetration testing. This is my project [goHackTools](https://github.com/dreddsa5dies/goHackTools), it has more than 400 stars. I looked and did not find a similar. I hope that this pull request will be accepted. Good luck with your work.
> add code examples

- README.md
This commit further cleans the new Industrial Control and SCADA Systems
section by providing a clearer description of the ISF line item, fixing
minor whitespace spacing issues, and clarifying the section's header.
> Add s7scan, a Siemens S7 PLC network scanner.

- README.md
Some of the issues highlighted by the pull request comment in
https://github.com/sindresorhus/awesome/pull/1366#issuecomment-455992262
are not what I would consider real issues. For instance, the issue
described by "Link to http://mvfjfugdwgc5uwho.onion/ is dead" is not
true; the link is not dead, but the automated linter they use does not
understand how to access Onion sites, so I didn't fix it. `¯\_(ツ)_/¯`
Other issues, however, the ones I consider legitimate, are addressed by
this commit. This includes fixing the letter case of section headings,
matching section headings with their Table of Contents heading, fixing
actually dead links, and so on. What I did not fix were issues that I
consider bugs in the linter.
> This commit addresses numerous issues for sindresorhus/awesome#1366.

- README.md
[Legion](https://github.com/GoVanguard/legion) -  Open source semi-automated discovery and reconnaissance network penetration testing framework by @GoVanguard
> Added Legion to Network Vulnerability Scanners

- .travis.yml
- README.md
Regarding #86 
Ideally makes things ready for https://github.com/sindresorhus/awesome/pull/1366
> Awesome Linting

- README.md
Saw an article about a new windows VM for red team testing that might be useful...
> Adding Command VM

- README.md
I've gathered a pretty comprehensive awesome-list of Shodan search queries I use often, as well as some others that are out-of-the-ordinary and interesting (and frightening!):
https://github.com/jakejarvis/awesome-shodan-queries
Please feel free to reject this if it isn't relevant here and/or mature enough. Thanks for the great list! 😊
> Add Shodan search queries list

- README.md
Recommend this list of AWS tools for offensive and defensive teams.
> Add AWS Tool Arsenal

- README.md
This PR implements the changes described in [this review request](https://github.com/enaqx/awesome-pentest/pull/337#pullrequestreview-343377822).
> Collab tools update: add Dradis and Lair from #337.

- README.md
Added a section for documentation tools, including the 3 most used documentation tools.
> Add Documentation Tools section

- README.md
This is a new commit in the interests in speed and brevity; the original
PR contained numerous extranneous commits. I asked the original
submitter to clean it a little bit, but they never responded, and now
their commit history requires quite a bit of conflict resolution before
it will merge cleanly. I'm taking the initiative to re-do their work in
a single, new commit just to have it done.
> Add Awesome Red Teaming.

- README.md
https://github.com/NorthwaveNL/fridax
> Add `Fridax` to the Reverse Engineering Tools.

- README.md
It's very old but the author points to LFISuite
> Modified Kadabra to LFISuite

- README.md
Update Asia Conferences and Event.
> Update Asia Conferences and Event

- README.md
Remove dead link from the README.
> Remove deadlink

- README.md
This list is an important piece of the full pentest puzzle. While this
list focuses primarily on the pre-exploitation and exploitation phases
of a penetration test, the Awesome Malware list focuses on
post-exploitation tools and resources, which are needed to make any
meaningful use of success with the tools listed on this list.
> Add Awesome Malware list to "Other Lists Online."

- README.md
QueenSono is based on ICMP protocol which commonly less monitored than other protocols. 
The binary approach is also useful as similar tools often use python, which could be a problem if we don't have it installed on the target machine.
> Add QueenSono in data exfiltration tool

- README.md
Add Reconmap under the Multi-paradigm frameworks section
https://github.com/Reconmap
https://reconmap.org
> Add Reconmap under the Collaboration tools section

- README.md
docs: correct the description for scancannon
> Correct the description for ScanCannon

- README.md
Hive - Self hosted pentest team collaboration framework and reporting tool
> Add Hexway Hive into Collaboration Tools section

- README.md
Pentest-Ground is a free plaground with vulnerable web apps for scanning and exploiting.
> Pentest-Ground

- README.md
[Ronin](https://github.com/ronin-rb) does indeed provide all of those features and is worth of being added to the "Multi-paradigm Frameworks" section; the new [recon engine](https://github.com/ronin-rb/ronin-recon#readme) is technically in Open Beta until July 22nd, but you can do manual recon with the various commands for the time being.
> Add Ronin to the "Multi-paradigm Frameworks" section

- README.md
What it says on the tin :)
Just adding https://pentestreports.com to the reports section. The website includes reports, templates and few other useful things
> Update README.md to add pentestreports.com

- README.md
Hi,
I’d like to suggest adding [Agentic Radar](https://github.com/splx-ai/agentic-radar) — an open-source CLI tool for security analysis of agentic AI workflows. It supports frameworks like LangGraph, CrewAI, n8n, OpenAI Agents and others.
The tool can:
- Scan agentic AI workflow source code
- Detect vulnerabilities (CVE, OWASP)
- Generate interactive visualizations with remediation suggestions
I think you might find the tool to your liking. It's a static code analysis tool that outputs CVEs and OWASPs for popular agentic AI workflows.
> Add Agentic Radar to Static Analyzers
