README.md
Python tools for penetration testers has moved to https://github.com/dloss/python-pentest-tools
=> "Python tools for penetration testers" url change

README.md
Routersploit is a tool similar to metasploit, but adapt to router exploitation. The project is really active.
=> Add routersploit in penetration testing tools

README.md
Doesn't seem to be available anymore
https://hub.docker.com/r/usertaken/archlinux-pentest-lxde/
[ldionmarcil:~]$ sudo docker pull usertaken/archlinux-pentest-lxde
Using default tag: latest
Pulling repository docker.io/usertaken/archlinux-pentest-lxde
Error: image usertaken/archlinux-pentest-lxde not found
=> Removed usertaken/archlinux-pentest-lxde docker (404)

README.md
adding OSINT-Framework (http://osintframework.com/) and Intel Techniques (https://inteltechniques.com/menu.html) to OSINT List
=> add OSINT-Framework to OSInt List

README.md
I'd like to propose adding "File Format Analysis Tools" section that goes somewhere close to "Hex Editors", but serves a slightly different purpose.
There's a few nice tools that allow us to dissect, analyze, visualize and potentially work on reverse engineering of arbitrary binary file formats. This is generally an important part of any large pentest project, especially if we're working on some closer-to-hardware stuff, where the data of the systems we're trying to attack is not all human-readable JSON and XML, but laid out in some (usually proprietary) file formats.
Partially, it can be done with advanced hex editors, such as Hexinator and/or 010 Editor, but it many cases it's more useful to access that data programmatically. As a start of category, I've chosen 3 most awesome projects I …
=> Added "File Format Analysis Tools" section (+3 tools)

README.md
Changed docker-metasploit link (and thus author) due to a 404 error in the prior link
=> Fixed broken metasploit link

README.md
I wanted to add the custom wordlist generator, CeWL, but there was no good section in which to put it, so I generalized the "Crackers" section to be "Hash Cracking Tools" since this is both more consistent with the other section headings that already exist and also provides a space where cracking utilities, beyond just hashing tools, can be sensibly added.
=> Retitle "Crackers" to "Hash Cracking Tools" and add CeWL project.

README.md
New section OSINT Resources for link-sites rather than actual tools.
This commit adds a new subsection under "Online Resources" called "OSInt Resources" and moves a few entries from the "OSInt Tools" section there. This is done because the OSInt Tools section has grown to expand entries that are not actually tools, but rather lists/collections of other tools. These OSINT resources are great, but are distinct from a single, installable, or otherwise immediately-usable tools.
This commit also adds a new such resource, NetBoomcamp.org's listing of OSINT tools and custom Web interfaces for some endpoints, like Facebook.
=> Group OSINT collections (rather than tools) in their own section, add a new collection, fix link for HackThisSite.org.

README.md
OWASP Zed Attack Proxy should be side-by-side with BurpSuite since both are specifically *HTTP* intercepting proxies. While they can be used for some lightweight "vulnerability scanning" (spidering, etc.) they are really more specifically *Web* tools.
=> Fix `redsnarf` link, remove duplicate Empire entry, recategorize ZAP.

README.md
One category I've noticed is conspicuously missing from this list is the set of tools requiring physical access. These include the LAN Turtle, USB Rubber Ducky, and Poisontap. I'm sure there are more but these are the big three that I know about and would like to see added first.
=> Add "Physical Access Tools" section with three example tools.

README.md
This commit tidies some minor issues with pull request #141, namely:
* fix style guide compliance from accidental reversion during merge.
* add a period to the last sentence of the introduction paragraph.
* make the table of contents's content match the headings in the doc.
* consistently spell open source without a dashed word ("open-source").
=> Make grammar consistent: "command-line" -> "command line" and so on.

.travis.yml, README.md
This pull request addresses the Awesome List style guide compliance issues against the Vulnerability Databases section. As before, descriptions have been added and acronyms in item links have been expanded. Additionally:
* Mozilla Foundation Security Advisories has been added to the list, since Firefox is a massive target.
* Microsoft Security Response Center links have been modified to link directly at their search forms.
* Mitre's CVE listing has been added.
* Fixed the link to the Inj3ct0r exploit marketplace and added its Onion service `.onion` domain, as well.
* Re-ordered the list with the most widely known items at the top. (This is somewhat arbitrary but I think my ordering will not be too controversial.)
* Note that OSVDB is historical-only, now; it no longer accepts new …
=> Style guide compliance pass focused on Vulnerability Databases section.

README.md
This commit provides more detail and context for the vulnerability
scanners section. It groups Web Scanners into its own subheading, and
moves scanning tools from the Web Exploitation section into this section
as these tools do not actually focus on *exploiting* websites.
Additionally, Static Analyzers are grouped, two new static analyzers
(cppcheck and FindBugs) have been added, and commercial tools are
appropriately described as such.
=> Reorganize Vulnerability Scanners section, add subheadings.

README.md
See [discussion](https://github.com/enaqx/awesome-pentest/pull/148#discussion_r126525306) for details and rationale.
=> Drop link to commercial-only VulnDB based off OSVDB.

README.md
This commit removes the "Basic Penetration Testing Tools" section and
moves numerous items listed therein into more appropriate places, based
on existing categories. For instance, BeEF is moved to the Web
Exploitation section, since it is more accurate to describe it as a Web
exploitation tool than a "Basic" tool. The former category is
descriptive while the latter is clearly nondescript.
A new section, "Multi-paradigm Frameworks," has been added for items
that were listed under the removed "Basic" section but that do not
cleanly fit into an existing category. Namely, these are Metasploit,
ExploitPack, and Faraday, which are exceptions simply because they are
so versatile. (Hence the choice of the new section, "Multi-paradigm.")
Additionally, the well-known Armitage GUI for Metasploit was …
=> Recategorize "Basic" tools section for clarity and conformity.

README.md
This commit updates numerous tools all previously categorized as "SSL"
tools. It updates their descriptions to more accurately describe current
versions by remarking on TLS capabilities, and it does the same with the
section heading. Further, Web-centric exploitation tools related to
SSL/TLS implementations have been moved to the Web Exploitation section,
where they arguably more properly belong, as SSL/TLS implementations may
include application-layer services beyond simply HTTP and "Web" traffic.
=> Move `sslstrip` to Web Exploitation, recategorize SSL as TLS tools.

README.md
I noticed that completely missing from this list are side-channel attack vectors and tools to aid in their discovery and exploitation, so, I'm adding some that I know about. These may not be the most "awesome" tools in this category, simply the ones I'm aware of.
=> Add ChipWhisperer, a side-channel attack toolchain, in new section.

README.md
This commit focses on the Penetration Testing Resources section and
provides better descriptions for most of the items therein. It also adds
the OSSTMM version 3 pentest methodology manual, which seems fitting as
it is both listed by OWASP and fits nicely with the PTES and PTF items
already listed.
=> Expand acronyms, improve descriptions, add OSSTMM item.

README.md
[ACSTIS](https://github.com/tijme/angularjs-csti-scanner) helps you to scan certain web applications for AngularJS Client-Side Template Injection (sometimes referred to as CSTI, sandbox escape or sandbox bypass). It supports scanning a single request but also crawling the entire web application for the AngularJS CSTI vulnerability.
=> Added ACSTIS to Web Scanners

README.md
Remove line 562 "* [Hack3rCon](http://hack3rcon.org/) - Annual US hacker conference." because the link leads to a domain squatting website rather than an actual hacker conference.
=> Remove Dead Link From List- "Hack3rcon"

README.md
Iodine is a DNS tunnel and useful for data exfiltration.
The Network Tools section became very long, so I chunked it up with
subcategories that pertain to the sort of tool. ("Network Tools" is
itself somewhat vague, and multi-paradigm/multi-function tools were
retained in the root of the category.)
Finally, "Defense Evasion Tools" was renamed to "Anti-virus Evasion
Tools" because every utility listed there was actually an AV or
host-based defense evasion tool, which is distinct from the network
evasion tools (exfiltration utilities) already listed in the "Network
Tools" section, above. I believe this clarity will help a reader more
quickly find the specific type of "defense evasion" utility they are
actually looking for.
=> Sub-categorize "Network Tools" section, clarify "Defense," add Iodine.

README.md
This PR contains two small changes related to DNS recon tools:
* The Amass subdomain enumeration tool's repository has moved to its new home in the OWASP organization. This PR updates the link to this tool in our list.
* One of the most famous DNS enumeration tools, `fierce.pl`, has been ported to Python3 but retains the same interface, and I think is awesome enough to be included here.
=> Amass is now an official OWASP project. Add Python3 port of `fierce`.

README.md
The "Hex Editors" section contained zero (nil, zilch, nada, none) hex editors that could be run by GNU/Linux users. Let's add some.
=> Add some good hex editors for GNU/Linux: Bless, wxHexEditor, `hexedit`.

README.md
A [ReDoS attack](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) is a denial of service condition executed by exploiting the nature of certain regular expression engines that require exponential time to compute a given input. This tool is a static analyzer that searches through source code and reports risk levels for any regular expressions found.
=> Add RegEx-DoS, an analyzer for regular expressions susceptible to DoS attacks.

README.md
This tool can connect to a domain over HTTP or SMTP, or search Certificate
Transparency (CT) logs in order to create a directed graph that
visualizes a domain's certificate's certificate alternative names. These
are other domain names that the certificate can be used to authenticate,
even if those domain names are not in public DNS records. Can be used as
an OSINT investigative tool as a task in the reconnaisance phase of a
pentesting engagement in order to easily discover additional targets.
=> Add CertGraph, crawl TLS certs for certificate alternative names.

.travis.yml, README.md
This commit fixes numerous CI build issues related to stale or broken
links. These include:
* Removal of Zoom username enumeration tool, covered by WPScan anyway.
* Removal of old Google dork database that is unmaintained/has vanished.
* Removal of `OSVDB.org` zone, which no longer resolves via DNS.
* Fix link to NoSQLmap tool (domain expired, use GitHub.com link now).
* Update link to Social Engineering in IT book from legacy URL.
* Update link to OWASP's AppSecUSA conference; now uses second-level domain.
Further, this commit simplifies the `.travis.yml` file in order to use a
plainer (more standard) certificates bundle. Two URLs have been added to
the whitelist: `www.shodan.io`, which returns a 403 Forbidden error when
accessed by Awesome Bot, and `www.mhprofessional.com`, which …
=> Fix Travis CI build errors, largely due to stale links.

README.md
Hwacha is a post-exploitation (credentials or keys obtained) tool that uses SSH to execute payloads or collect artifacts from one or multiple hosts at a time.
=> Adding Hwacha to GNU/Linux utilities

README.md
This commit adds a new utility, `shellpop`, which is a Python script
that is used to generate sophisticated shellcode in numerous languages.
It also removes trailing whitespace from several line items, likely
added by mistake, capitalizes the name of the programming language Rust,
and rephrases the description of Hwacha for clarity and conciseness.
=> Add `shellpop`, remove trailing whitespace, fix minor grammar errors.

README.md
https://github.com/stevenaldinger/decker
Decker allows writing declarative "penetration tests as code". It uses the same config language as Terraform and other Hashicorp tools and has a plugin based architecture so the usefulness of the framework will grow as more plugins become available. The [all-the-things](https://github.com/stevenaldinger/decker/blob/master/examples/all-the-things.hcl) example will take a target hostname and run web app scans such as SSL vulnerability and WAF detection as well as general info gathering, ftp, smtp, imap, vnc, mysql, and postgres scans if the relevant ports are found to be open in the nmap scan.
Docker images are also provided and the `stevenaldinger/decker:kali` image is recommended since it has a lot of tools preinstalled.
=> Add Decker orchestration framework to multi-paradigm frameworks

.travis.yml, README.md
This commit also adds GhostProject.fr to the whitelist, as they use
CloudFlare's JavaScript DDoS detection and return an HTTP 503 error.
This commit also removes `zoomeye.org` from the whitelist,
because they seem to be returning HTTP 200 OK responses reliably now.
=> Fix Awesome-Bot build errors: ComputerSecurityStudent.com is gone.

README.md
This commit makes a substantial change by moving two sections that were
previously in "Tools" into the "Online Resources" category instead.
Specifically, the "Penetration Testing Report Templates" and "Code
examples for Penetration Testing" sections, each of which contained
references to documents rather than immediately-usable software, were
moved out of the "Tools" category. This was done because there is now a
clear distinction between "places to go to get more information about a
topic" (a resource) and "software to download that is immediately usable
in a pentest" (a tool).
Additionally, this commit adds a new section of Tools for pentests
tentatively called "Collaboration Tools" and adds RedELK, a Red Team's
SIEM, to that section. RedELK is an example of a multiple teamserver …
=> General re-organization of some Tools sections, adds several tools.

README.md
This commit removes the bolding from the Netsparker referral link
because it lints as a heading. (The referral URL itself was not
deleted.) It also adds the word `culture` at the end of the 2600 list
item so that line item won't end in a quotation mark, but a period (as
the pedantic linter requires). This commit also fixes the headline level
for the License section and uses the new Awesome badge SVG sources.
=> Address numerous Awesome linter errors for sindresorhus/awesome#1366 PR.

.travis.yml, README.md
In this commit, the primary change is alphabetizing both the table of
contents as well as the line items for each category. This is done in
order to make it easier for readers to locate their desired information
with their naked eyes. The list is long, and as such should at least
have a consistent scheme for ordering the items within it.
Alphabetization also side-steps the issue of favoritism since the sort
order is lexicographical.
Additionally, this commit changes several headings to more clearly
describe its contents. For example, most of the subheadings under the
"Online Resources" category have been renamed to "Online [Topic]
Resources", where "[Topic]" was the old heading. Similarly, I split the
Docker Container section into two, one for distros and for tools, since
the previous …
=> This commit proposes a massive reorganization of the list categories.

.travis.yml, README.md
This PR merges work on a new section for Android-based software, which includes the cSploit integrated Metasploit app, the AOPP custom ROM build system and software ports, and the Fing network scanner.
Additionally, a couple of commits work on fixing Travis CI build errors. This includes adding `www.parrot.org` to the URL whitelist due to their new use of the Cloudflare WAF, and an updated URL for the Immunity Debugger line item.
=> Add new Android section and three tools to it, fix a couple build errors.

README.md
This pull request also includes a fix for the `dos-over-tor` tool which otherwise returns an HTTP 404 Not Found error.
=> Add SIET, tool for manipulating insecure Cisco Smart Install switches.

README.md
I added the National Cyber Summit Conference to the Conference List due to it being a great resource for learning about new technologies and talking to experts, but also because it has an annual Capture the Flag event.
=> Add National Cyber Summit Conference to the Conference List

README.md
This PR proposes a by-continent categorization scheme for the "Conferences and Events" section because that section is getting somewhat long and unwieldy. I am suggesting "by continent" as a subcategorization scheme because it feels appropriately sized and also offers visibility into which areas of the world are perhaps underrepresented in this list.
=> Subcategorize "Conferences" section by continent.

.travis.yml, README.md
This PR fixes many issues with the Travis CI build, ultimately removing a number of whitelisted URLs in favor of updated link content. Along that line, some links were removed (Intel Techniques no longer exists), some were updated (links that were 404'ing have been updated), etc.
AQUATONE and OWASP Amass have been recategorized as network recon tools, a new tool (subbrute) was added to that same section, and the Travis build environment uses an updated Travis CI configuration file with a more modern default Ruby installation.
=> Add subbrute, recategorize some tools, fixup Travis build.

.travis.yml
This PR suggests allowing HTTP 503 Service Unavailable errors because of how frequently Amazon.com returns these errors to `awesome_bot`. Additionally, the `ghostproject.fr` domain, which was previously whitelisted, also returns this error due to their Cloudflare configuration.
I suggest that by allowing 503 errors, which are *usually* indications of temporary outages rather than permanent problems, we can shorten the awesome_bot whitelist, allow the Travis build to succeed, and yet still maintain an accurate view of link rot.
=> Amazon.com says HTTP 503 often, so allow that but do not whitelist.

README.md
PSKracker is a WPA/WPA2/WPS cracker for pentesters. The Distributed Weakness Filing project was [terminated by the creator on March 7th, 2019](https://twitter.com/kurtseifried/status/1103858442479910913), just over a year ago. Now their infrastructure is returning HTTP error codes that fail the build. This pull request includes a commit that removes the DWF project from this list.
=> Add PSKracker, remove DWF.

README.md
Shellphish should either be removed or the link updated as the original repository is not available anymore
=> Update link to shellphish

README.md
This is a work in progress PR showing a direction for consolidating numerous list sections and more clearly categorizing certain tools. The major goals of this work are:
* Lessen ambiguous areas such as "other lists elsewhere" and "network tools" that have grown long and less clear over time.
* More clearly delineate the purpose of a given tool or resource. For example, some items are clearly "educational" (labs, books, intentionally vulnerable systems, so forth) while others are "reference," and there are several places where these intentions are mixed.
* Ensure each block items listed are appropriate for the heading and all its ancestor headings. (For example, steganography tools that don't touch a network shouldn't be in the "network tools" section.)
Some of the techniques I'll use for …
=> Reorganization of sections, consistency fixes across headings and contents.

README.md
OpalOPC is a vulnerability scanner developed by myself. It targets the OT protocol OPC UA. It is free for non-commercial use.
=> Add OpalOPC

README.md
Reconmap's URL changed from .org to .com, so I have updated it accordingly, since there is no redirect on the .org domain.
=> Updated Reconmap URL from org to com

README.md
Update to Dradis website link to reflect the new domain they are using
=> Update Dradis website link to reflect new domain used
